DROP TABLE IF EXISTS heartrate;

CREATE TABLE heartrate(
    [id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [time] TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    [name] STRING NOT NULL,
    [value] INTEGER NOT NULL
);